INSERT INTO airline (callsign, name, country) VALUES
('Q5', '40-Mile Air', 'United States'),
('AQ', 'Aloha Airlines', 'United States'),
('AA', 'American Airlines', 'United States'),
('G4', 'Allegiant Air', 'United States'),
('AC', 'Air Canada', 'Canada'),
('KO', 'Alaska Central Express', 'United States'),
('2Q', 'Air Cargo Carriers', 'United States'),
('ZW', 'Air Wisconsin', 'United States'),
('QK', 'Air Canada Jazz', 'Canada'),
('4N', 'Air North Charter - Canada', 'Canada'),
('JW', 'Arrow Air', 'United States'),
('EV', 'Atlantic Southeast Airlines', 'United States'),
('MQ', 'American Eagle Airlines', 'United States'),
('ZA', 'Access Air', 'United States'),
('QH', 'Air Florida', 'United States'),
('5Y', 'Atlas Air', 'United States'),
('FL', 'AirTran Airways', 'United States'),
('TS', 'Air Transat', 'Canada'),
('JV', 'Bearskin Lake Air Service', 'Canada'),
('CH', 'Bemidji Airlines', 'United States'),
('8E', 'Bering Air', 'United States'),
('CP', 'Canadian Airlines', 'Canada'),
('CN', 'Canadian National Airways', 'Canada'),
('9K', 'Cape Air', 'United States'),
('RP', 'Chautauqua Airlines', 'United States'),
('DQ', 'Coastal Air', 'United States'),
('9L', 'Colgan Air', 'United States'),
('OH', 'Comair', 'United States'),
('C5', 'CommutAir', 'United States'),
('CO', 'Continental Airlines', 'United States'),
('CS', 'Continental Micronesia', 'United States'),
('DL', 'Delta Air Lines', 'United States'),
('EZ', 'Evergreen International Airlines', 'United States'),
('EO', 'Express One International', 'United States'),
('XE', 'ExpressJet', 'United States'),
('5T', 'Canadian North', 'Canada'),
('RF', 'Florida West International Airways', 'United States'),
('FP', 'Freedom Air', 'United States'),
('F9', 'Frontier Airlines', 'United States'),
('2F', 'Frontier Flying Service', 'United States'),
('G7', 'GoJet Airlines', 'United States'),
('ZK', 'Great Lakes Airlines', 'United States'),
('H6', 'Hageland Aviation Services', 'United States'),
('HA', 'Hawaiian Airlines', 'United States'),
('HP', 'Hawaiian Pacific Airlines', 'United States'),
('C2', 'CanXplorer', 'Canada'),
('C1', 'CanXpress', 'Canada'),
('QX', 'Horizon Air', 'United States'),
('I9', 'Indigo', 'United States'),
('IS', 'Island Airlines', 'United States'),
('QJ', 'Jet Airways', 'United States'),
('B6', 'JetBlue Airways', 'United States'),
('M5', 'Kenmore Air', 'United States'),
('BZ', 'Keystone Air Services', 'Canada'),
('KP', 'Kiwi International Air Lines', 'United States'),
('YV', 'Mesa Airlines', 'United States'),
('XJ', 'Mesaba Airlines', 'United States'),
('JI', 'Midway Airlines', 'United States'),
('YX', 'Midwest Airlines', 'United States'),
('YC', 'Ciel Canadien', 'Canada'),
('EJ', 'New England Airlines', 'United States'),
('7F', 'First Air', 'Canada'),
('H3', 'Harbour Air (Priv)', 'Canada'),
('NW', 'Northwest Airlines', 'United States'),
('BH', 'Hawkair', 'Canada'),
('OY', 'Omni Air International', 'United States'),
('JB', 'Helijet', 'Canada'),
('LW', 'Pacific Wings', 'United States'),
('KS', 'Peninsula Airways', 'United States'),
('PI', 'Piedmont Airlines (1948-1989)', 'United States'),
('9E', 'Pinnacle Airlines', 'United States'),
('1X', 'Island Express Air', 'Canada'),
('BK', 'Potomac Air', 'United States'),
('RW', 'Republic Airlines', 'United States'),
('RD', 'Ryan International Airlines', 'United States'),
('BB', 'Seaborne Airlines', 'United States'),
('SY', 'Sun Country Airlines', 'United States'),
('N5', 'Skagway Air Service', 'United States'),
('WN', 'Southwest Airlines', 'United States'),
('WG', 'Sunwing Airlines', 'Canada'),
('AL', 'Skywalk Airlines', 'United States'),
('1I', 'Sierra Nevada Airlines', 'United States'),
('NK', 'Spirit Airlines', 'United States'),
('OO', 'SkyWest', 'United States'),
('S5', 'Shuttle America', 'United States'),
('AX', 'Trans States Airlines', 'United States'),
('U5', 'USA3000 Airlines', 'United States'),
('UA', 'United Airlines', 'United States'),
('U7', 'USA Jet Airlines', 'United States'),
('US', 'US Airways', 'United States'),
('UH', 'US Helicopter Corporation', 'United States'),
('VX', 'Virgin America', 'United States'),
('WA', 'Western Airlines', 'United States'),
('WO', 'World Airways', 'United States'),
('J3', 'Northwestern Air', 'Canada'),
('KW', 'Carnival Air Lines', 'United States'),
('WP', 'Island Air (WP)', 'United States'),
('8P', 'Pacific Coastal Airline', 'Canada'),
('PD', 'Porter Airlines', 'Canada'),
('FA', 'Epic Holiday', 'United States'),
('TQ', 'Texas Wings', 'United States'),
('A1', 'Atifly', 'United States'),
('RY', 'Rainbow Air Canada', 'Canada'),
('QY', 'Red Jet Canada', 'Canada'),
('RS', 'Sky Regional', 'Canada'),
('3E', 'Air Choice One', 'United States'),
('ZQ', 'Locair', 'United States'),
('K5', 'SeaPort Airlines', 'United States'),
('S6', 'Salmon Air', 'United States'),
('J5', 'Alaska Seaplane Service', 'United States'),
('6P', 'Gryphon Airlines', 'United States'),
('WQ', 'PanAm World Airways', 'United States'),
('5G', 'Skyservice Airlines', 'Canada'),
('Y1', 'Yellowstone Club Private Shuttle', 'United States'),
('T6', 'Trans Pas Air', 'United States'),
('HI', 'Papillon Grand Canyon Helicopters', 'United States'),
('E1', 'Usa Sky Cargo', 'United States'),
('9T', 'Transwest Air', 'Canada'),
('7H', 'Era Alaska', 'United States'),
('H1', 'Hankook Air US', 'United States'),
('YR', 'SENIC AIRLINES', 'United States'),
('B0', 'Aws express', 'United States'),
('76', 'Southjet', 'United States'),
('77', 'Southjet connect', 'United States'),
('78', 'Southjet cargo', 'United States'),
('P4', 'Patriot Airways', 'United States'),
('V2', 'Vision Airlines (V2)', 'United States'),
('YE', 'Yellowtail', 'United States'),
('KG', 'Royal Airways', 'United States'),
('TJ', 'T.J. Air', 'United States'),
('M1', 'Maryland Air', 'United States'),
('ZM', 'Apache Air', 'United States'),
('N8', 'National Air Cargo', 'United States'),
('13', 'Eastern Atlantic Virtual Airlines', 'United States'),
('8O', 'West Coast Air', 'Canada'),
('XA', 'XAIR USA', 'United States'),
('RN', 'Rainbow Air (RAI)', 'United States'),
('WS', 'WestJet', 'Canada'),
('RX', 'Rainbow Air Polynesia', 'United States'),
('RM', 'Rainbow Air US', 'United States'),
('S0', 'Spike Airlines', 'United States'),
('A2', 'All America', 'United States'),
('KZ', 'Dense Connection', 'United States'),
('WR', 'WestJet Encore', 'Canada'),
('J1', 'OneJet', 'United States'),
('W1', 'World Experience Airline', 'Canada'),
('Z4', 'Zoom Airlines', 'Canada'),
('4B', 'Boutique Air (Priv)', 'United States'),
('LE', 'Liberty Airways', 'United States'),
('3M', 'Silver Airways (3M)', 'United States'),
('W3', 'World Scale Airlines', 'United States'),
('AG', 'All America US', 'United States')
;
