
BEGIN;

DROP DOMAIN IF EXISTS iata_code CASCADE;
DROP DOMAIN IF EXISTS airline_code CASCADE;

DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS airport CASCADE;
DROP TABLE IF EXISTS airline CASCADE;
DROP TABLE IF EXISTS flight CASCADE;
DROP TABLE IF EXISTS flight_schedule CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS payment_method CASCADE;
DROP TABLE IF EXISTS flight_class CASCADE;
DROP TABLE IF EXISTS customer_address CASCADE;

DROP OWNED BY aero CASCADE;
DROP USER aero;

COMMIT;