
BEGIN;

DROP DOMAIN IF EXISTS iata_code CASCADE;
DROP DOMAIN IF EXISTS airline_code CASCADE;

DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS airport CASCADE;
DROP TABLE IF EXISTS airline CASCADE;
DROP TABLE IF EXISTS flight CASCADE;
DROP TABLE IF EXISTS flight_schedule CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS payment_method CASCADE;
DROP TABLE IF EXISTS flight_class CASCADE;
DROP TABLE IF EXISTS customer_address CASCADE;

DROP FUNCTION IF EXISTS aero_approx_distance_mi(lat1 float, long1 float, lat2 float, long2 float);
DROP FUNCTION IF EXISTS aero_ticket_price(distance FLOAT);
DROP FUNCTION IF EXISTS aero_get_bit_positions(b bit varying);

DROP OWNED BY aero CASCADE;
DROP USER aero;

COMMIT;